evaluation:
  dimensions:
    task:
      weight: 0.30
      sub_criteria:
        - programming_language_specified
        - requirements_clarity
        - architecture_guidance
        - code_quality_standards
    context:
      weight: 0.25
      sub_criteria:
        - project_context_provided
        - technical_constraints_specified
        - target_developer_audience
        - existing_codebase_context
    references:
      weight: 0.20
      sub_criteria:
        - code_examples_provided
        - api_documentation_referenced
        - test_expectations_defined
    constraints:
      weight: 0.25
      sub_criteria:
        - error_handling_requirements
        - security_considerations
        - performance_requirements
        - scope_exclusions

  grading_scale:
    excellent: 85
    good: 65
    needs_work: 40
    weak: 0
